name: Simple Workflow

on:
  push:
    branches: [ "dev" ]   # Runs when code is pushed to dev

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "Hello from GitHub Actions! "
